"""Regenerate wiki/index.md from page frontmatter.

Usage: python tools/build_index.py
Run after every ingest / new page. Hand-written content belongs in overview.md, not here.
"""
import os
import sys
from collections import defaultdict
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wikilib import WIKI, frontmatter, wiki_pages  # noqa: E402

SECTIONS = [('concepts', 'Concepts'), ('applications', 'Applications'), ('tools', 'Tools & software'),
            ('comparisons', 'Comparisons & syntheses')]


def main():
    pages = wiki_pages()
    L = ['# Index — MPPI SOTA knowledge base', '',
         '_Generated by `tools/build_index.py` on %s. Do not edit by hand._' % date.today().isoformat(), '',
         'Start here: [[overview]] · history: [[log]] · schema: `../CLAUDE.md` · deliverable: `../latex/main.tex`', '']
    for folder, title in SECTIONS:
        L += ['## ' + title, '']
        for slug in sorted(s for s in pages if s.startswith(folder + '/')):
            fm, _ = frontmatter(pages[slug])
            L.append('- [[%s]] — %s' % (slug, fm.get('title', slug).strip('"')))
        L.append('')
    prj = sorted(s for s in pages if s.startswith('project/'))
    L += ['## Project documents (%d) — internal, not citable' % len(prj), '']
    if prj:
        L += ['| Page | Title | Type | Date | Status |', '|---|---|---|---|---|']
        for slug in prj:
            fm, _ = frontmatter(pages[slug])
            L.append('| [[%s]] | %s | %s | %s | %s |' % (slug, fm.get('title', '').strip('"'), fm.get('doctype', ''),
                                                        fm.get('date', ''), fm.get('status', '')))
    else:
        L.append('_None yet. Add with `python tools/add_project_doc.py`._')
    L.append('')
    by_tag = defaultdict(list)
    rows = []
    for slug in sorted(s for s in pages if s.startswith('sources/')):
        fm, _ = frontmatter(pages[slug])
        tags = [t.strip() for t in fm.get('tags', '[]').strip('[]').split(',') if t.strip()]
        rows.append((fm.get('year', ''), slug, fm.get('title', '').strip('"'), fm.get('status', ''),
                     'pdf' if fm.get('pdf', 'none') != 'none' else '-'))
        for t in tags:
            by_tag[t].append(slug)
    L += ['## Sources (%d)' % len(rows), '', '| Year | Page | Title | Status | PDF |', '|---|---|---|---|---|']
    for y, slug, t, st, pdf in sorted(rows, key=lambda r: (r[0], r[1]), reverse=True):
        L.append('| %s | [[%s]] | %s | %s | %s |' % (y, slug, t, st, pdf))
    L += ['', '## Sources by tag', '']
    for t in sorted(by_tag):
        L.append('- **%s**: ' % t + ', '.join('[[%s]]' % s for s in by_tag[t]))
    L.append('')
    open(os.path.join(WIKI, 'index.md'), 'w', encoding='utf8').write('\n'.join(L))
    print('index.md written with %d sources' % len(rows))


if __name__ == '__main__':
    main()
