"""Curated notes used to (re)generate wiki/sources/<key>.md stubs.

This file is the *seed* of the source pages. Once a page exists, the page itself is the
source of truth and should be edited directly (new_source.py never overwrites an existing page
unless --force is given).

Each entry: key -> dict(tags, tldr, method, evidence, relevance, concepts)
  concepts: list of wiki page slugs (relative to wiki/, without .md) the source supports.
"""

NOTES = {
# ------------------------------------------------------------------ foundations
'kappen2005pathintegrals': dict(
    tags=['foundations', 'theory'],
    tldr='Shows that, for control-affine dynamics and quadratic control cost with lambda*R^-1 = Sigma, the HJB equation becomes linear via V = -lambda log Psi; the solution is a path integral (Feynman-Kac) over uncontrolled trajectories.',
    method='Exponential transformation of the value function; Feynman-Kac representation; Monte-Carlo estimate of the optimal control as cost-weighted noise. Discusses symmetry breaking (multiple optimal solutions) as a function of noise level.',
    evidence='Analytical examples (delayed choice, symmetry breaking).',
    relevance='Theoretical root of every MPPI variant. The noise/cost coupling assumption explains why MPPI exploration and control penalty are tied together.',
    concepts=['concepts/path-integral-control']),
'theodorou2010pi2': dict(
    tags=['foundations', 'theory', 'learning'],
    tldr='PI^2: generalised path integral control for parameterised policies (DMPs); derives a probability-weighted policy-improvement rule with no gradients and only the temperature as open parameter.',
    method='Path-integral optimal control extended to parameterised policies; exponentiated cost-to-go weights per time step; applied to RL of motor skills.',
    evidence='Simulated and robotic learning tasks (robot dog, arm reaching).',
    relevance='Bridge from Kappen theory to robotics; the weighting rule is the same one later used by STOMP and MPPI.',
    concepts=['concepts/path-integral-control']),
'williams2015covariance': dict(
    tags=['foundations', 'mppi-core'],
    tldr='First MPPI formulation with covariance variable importance sampling: allows changing the sampling covariance independently of the control cost.',
    method='Importance sampling with a modified covariance in the path-integral expectation; GPU implementation.',
    evidence='Simulated cart-pole, quadrotor, race car.',
    relevance='Introduces the importance-sampling view that every later variant (Biased-MPPI, MPOPI) builds on.',
    concepts=['concepts/information-theoretic-mppi', 'concepts/sampling-distributions']),
'williams2016aggressive': dict(
    tags=['foundations', 'mppi-core', 'mobile'],
    tldr='Real-time MPPI on the AutoRally 1:5 rally car at the limits of handling, using GPU rollouts of a learned/physics model.',
    method='Continuous-time path-integral MPPI, thousands of samples on GPU, costmap-based track cost.',
    evidence='Real aggressive driving on dirt track.',
    relevance='Proof that sampling-based MPC can run in real time on non-smooth costs; seed of MPPI in mobile robotics.',
    concepts=['concepts/information-theoretic-mppi', 'applications/mobile-robots-amr']),
'williams2017jgcd': dict(
    tags=['foundations', 'mppi-core', 'gpu'],
    tldr='Journal version of MPPI: derivation from path-integral control and parallel (GPU) computation, generalised importance sampling.',
    method='Path-integral derivation, importance sampling with arbitrary nominal control, CUDA implementation.',
    evidence='Simulated cart-pole, quadrotor navigation, race car.',
    relevance='Canonical reference for the algorithm and its parallel implementation.',
    concepts=['concepts/path-integral-control', 'concepts/information-theoretic-mppi']),
'williams2017itmpc': dict(
    tags=['foundations', 'mppi-core', 'learning'],
    tldr='Information-theoretic derivation of MPPI in discrete time, removing control-affine assumption; used with learned neural-network dynamics (model-based RL).',
    method='Free-energy / KL bound, optimal distribution q*, KL projection onto Gaussian family; NN dynamics.',
    evidence='AutoRally real-world with learned dynamics.',
    relevance='The discrete-time form used in almost all modern implementations.',
    concepts=['concepts/information-theoretic-mppi', 'concepts/learning-augmented-mppi']),
'williams2018tro': dict(
    tags=['foundations', 'mppi-core', 'mobile'],
    tldr='T-RO consolidation of information-theoretic MPC: theory, the gamma = lambda(1-alpha) control-cost trade-off and extensive autonomous driving results.',
    method='Free energy and relative entropy duality; importance sampling update; learned dynamics; costmap.',
    evidence='AutoRally at high speed, simulations.',
    relevance='Primary citation for the MPPI update equation in the SOTA (Eq. 3).',
    concepts=['concepts/information-theoretic-mppi', 'applications/mobile-robots-amr']),
'williams2018tubemppi': dict(
    tags=['robustness'],
    tldr='Tube-MPPI: MPPI plans a nominal trajectory while an iLQG ancillary controller tracks it, robustifying against disturbances when the cost is sparse.',
    method='Nominal/actual state split; augmented importance sampling; iLQG tracking.',
    evidence='AutoRally real-world, sparse costs.',
    relevance='First "MPPI + classical controller" layering, analogous to MPPI + Core-IPC MPC in Plan4ARI.',
    concepts=['concepts/robustness-uncertainty', 'concepts/hybrid-gradient-sampling']),
'kazim2024survey': dict(
    tags=['survey'],
    tldr='Survey of path-integral control for trajectory optimisation: theory (KL, free energy, variational inference), algorithmic variants and applications.',
    method='Review.',
    evidence='Benchmark simulations of several variants.',
    relevance='Used to cross-check coverage of the SOTA. Good entry point for new team members.',
    concepts=['concepts/path-integral-control', 'concepts/information-theoretic-mppi', 'comparisons/mppi-variants-matrix']),
'wagener2019dmd': dict(
    tags=['theory'],
    tldr='Casts MPC as online learning; shows MPPI and CEM are instances of dynamic mirror descent (DMD-MPC) and derives new variants.',
    method='Online learning / mirror descent framework for sampling-based MPC.',
    evidence='Simulated cart-pole and AutoRally.',
    relevance='Theoretical link between MPPI, CEM and gradient-like updates; useful to justify step-size (alpha_u) choices.',
    concepts=['concepts/mppi-vs-mpc', 'concepts/information-theoretic-mppi']),
# ------------------------------------------------------------------ classical comparisons
'rawlings2017mpc': dict(tags=['mpc', 'background'], tldr='Reference textbook on MPC theory, computation and design (stability, recursive feasibility, robust/stochastic MPC, numerics).', method='Textbook.', evidence='-', relevance='Baseline for the MPPI vs MPC comparison.', concepts=['concepts/mppi-vs-mpc']),
'mayne2014mpc': dict(tags=['mpc', 'background'], tldr='Survey of MPC developments: stability, robustness, economic MPC, open problems.', method='Survey.', evidence='-', relevance='Cited for the guarantees that MPPI lacks.', concepts=['concepts/mppi-vs-mpc']),
'verschueren2022acados': dict(tags=['mpc', 'software'], tldr='acados: embedded NMPC/MHE software (SQP-RTI, HPIPM, code generation).', method='Software framework.', evidence='Benchmarks on embedded hardware.', relevance='Candidate gradient-based solver for the Core-IPC layer.', concepts=['concepts/mppi-vs-mpc', 'tools/software-ecosystem']),
'tassa2012ilqg': dict(tags=['ddp', 'background'], tldr='Online iLQG/DDP trajectory optimisation in MuJoCo with control limits for complex behaviours.', method='Box-constrained iLQG, receding horizon.', evidence='Humanoid simulation.', relevance='Gradient-based receding-horizon baseline; ancillary controller in Tube-MPPI.', concepts=['concepts/mppi-vs-mpc']),
'kalakrishnan2011stomp': dict(tags=['trajopt', 'background'], tldr='STOMP: gradient-free stochastic trajectory optimisation for motion planning using path-integral style weighting of noisy trajectories.', method='Sampling of smooth noisy trajectories, PI^2-like update.', evidence='PR2 arm planning.', relevance='Offline ancestor of MPPI for manipulators; still in MoveIt.', concepts=['concepts/mppi-vs-mpc', 'applications/industrial-manipulators']),
'zucker2013chomp': dict(tags=['trajopt', 'background'], tldr='CHOMP: covariant functional-gradient trajectory optimisation with signed-distance obstacle costs.', method='Covariant gradient descent.', evidence='Arms and legged robots.', relevance='Gradient-based trajectory optimisation baseline.', concepts=['concepts/mppi-vs-mpc']),
'schulman2014trajopt': dict(tags=['trajopt', 'background'], tldr='TrajOpt: sequential convex optimisation with convex-convex collision checking.', method='SQP with penalty, swept-volume collision.', evidence='Arms, humanoids.', relevance='Gradient-based baseline; strong at hard constraints.', concepts=['concepts/mppi-vs-mpc']),
'fox1997dwa': dict(tags=['mobile', 'background'], tldr='Dynamic Window Approach: samples admissible velocities in a dynamic window and scores them over a short horizon.', method='Velocity-space sampling.', evidence='Indoor robots.', relevance='Incumbent AMR local planner that MPPI is replacing in Nav2.', concepts=['concepts/mppi-vs-mpc', 'applications/mobile-robots-amr']),
'rosmann2017teb': dict(tags=['mobile', 'background'], tldr='Timed Elastic Band in distinctive topologies: parallel optimisation of multiple homotopy-class trajectories.', method='Sparse NLP per topology, selection.', evidence='Mobile robots.', relevance='Gradient-based AMR baseline; explicit multimodality via homotopies.', concepts=['concepts/mppi-vs-mpc', 'concepts/multimodality', 'applications/mobile-robots-amr']),
'rubinstein1999cem': dict(tags=['background', 'sampling'], tldr='Cross-entropy method for combinatorial and continuous optimisation.', method='Elite-sample refit of a parametric distribution.', evidence='-', relevance='CEM-MPC is the closest sibling of MPPI.', concepts=['concepts/mppi-vs-mpc']),
'faroni2019pik': dict(tags=['mpc', 'manipulators', 'industrial'], tldr='Predictive inverse kinematics for redundant manipulators with task scaling under kinematic constraints (CNR-STIIMA).', method='MPC-like QP over a horizon with task scaling.', evidence='Industrial redundant manipulators.', relevance='In-house Core-IPC component: certified reference generation downstream of MPPI.', concepts=['concepts/mppi-vs-mpc', 'applications/industrial-manipulators', 'comparisons/plan4ari-gap-analysis']),
'faroni2020scaling': dict(tags=['mpc', 'manipulators', 'industrial'], tldr='Predictive joint trajectory scaling for manipulators with kinodynamic constraints.', method='Predictive scaling of a reference under velocity/acceleration/torque limits.', evidence='Industrial manipulator experiments.', relevance='Candidate micro-interpolation/safety layer that makes MPPI references feasible.', concepts=['concepts/mppi-vs-mpc', 'applications/industrial-manipulators', 'comparisons/plan4ari-gap-analysis']),
# ------------------------------------------------------------------ sampling-based MPC siblings
'pinneri2020icem': dict(tags=['sampling', 'cem'], tldr='iCEM: improved CEM for real-time planning with coloured noise, elite memory and shifting.', method='CEM with time-correlated (coloured) noise.', evidence='Simulated locomotion and manipulation.', relevance='Coloured noise is a cheap smoothness fix also applicable to MPPI.', concepts=['concepts/mppi-vs-mpc', 'concepts/smoothness-action-parametrization']),
'howell2022predictivesampling': dict(tags=['sampling', 'software', 'simulator'], tldr='Predictive Sampling in MuJoCo MPC (MJPC): very simple best-sample sampling MPC is competitive with iLQG when using the physics engine as model.', method='Spline-parametrised sampling, keep best rollout.', evidence='Many MuJoCo tasks in real time.', relevance='Shows simulator-in-the-loop sampling MPC is viable; MJPC is a ready tool.', concepts=['concepts/physics-simulator-rollouts', 'tools/software-ecosystem', 'concepts/mppi-vs-mpc']),
'lambert2020svmpc': dict(tags=['multimodal', 'variational'], tldr='Stein Variational MPC: non-parametric particle approximation of the posterior over control sequences via SVGD, capturing multiple modes.', method='SVGD on a mixture of Gaussians over control sequences.', evidence='Simulated navigation, manipulation, real car.', relevance='Principled multimodality; heavier than MPPI.', concepts=['concepts/multimodality', 'concepts/sampling-distributions']),
'okada2020vimpc': dict(tags=['variational', 'learning'], tldr='Variational-inference MPC: MPPI/CEM as inference; mixture proposal for multimodality with Bayesian learned models.', method='VI-MPC with Gaussian mixtures.', evidence='Simulated tasks.', relevance='Inference view of MPPI; mixture proposals.', concepts=['concepts/multimodality', 'concepts/learning-augmented-mppi']),
'wang2021tsallis': dict(tags=['variational'], tldr='Generalises MPPI weighting with Tsallis divergence; yields a family including CEM-like thresholding and MPPI exponential weights.', method='Tsallis VI-MPC.', evidence='Simulated tasks.', relevance='Weighting function is a tunable design choice.', concepts=['concepts/information-theoretic-mppi', 'concepts/sampling-distributions']),
# ------------------------------------------------------------------ algorithmic variants
'gandhi2021rmppi': dict(tags=['robustness', 'guarantees'], tldr='Robust MPPI: augmented nominal/real state with iterative feedback, bound on free-energy growth giving performance guarantees.', method='Nominal state selection, ancillary feedback, theoretical bound.', evidence='AutoRally sim/real.', relevance='Only MPPI variant with explicit performance bounds; template for certified layering.', concepts=['concepts/robustness-uncertainty']),
'abraham2020emppi': dict(tags=['robustness', 'learning'], tldr='Ensemble MPPI: samples model parameters (domain randomisation) and adapts their distribution online for generalisation under parameter uncertainty.', method='Ensemble rollouts over parameters, risk-sensitive aggregation, online adaptation.', evidence='Simulated manipulation and locomotion.', relevance='Handles unknown payloads/friction in industrial tasks.', concepts=['concepts/robustness-uncertainty']),
'mohamed2025umppi': dict(tags=['robustness', 'mobile', 'safety'], tldr='U-MPPI: propagates mean and covariance with the unscented transform; risk-sensitive cost and better exploration.', method='Unscented transform sampling, risk-sensitive cost.', evidence='Simulated and real autonomous navigation.', relevance='Uncertainty-aware AMR navigation.', concepts=['concepts/robustness-uncertainty', 'applications/mobile-robots-amr']),
'yin2022covsteering': dict(tags=['robustness', 'sampling'], tldr='Covariance-steering MPPI: shapes the distribution of sampled trajectories (terminal covariance) for better sample efficiency.', method='Covariance steering of the sampling distribution.', evidence='Simulated race car.', relevance='Better use of sample budget.', concepts=['concepts/sampling-distributions', 'concepts/robustness-uncertainty']),
'yin2023shieldmppi': dict(tags=['safety', 'cbf'], tldr='Shield-MPPI: CBF cost terms plus a local repair (shield) of the MPPI solution to reduce constraint violations cheaply.', method='CBF-based cost and gradient-based local repair.', evidence='Aggressive racing sim and hardware.', relevance='Shows a cheap safety layer after MPPI.', concepts=['concepts/constraints-and-safety']),
'gandhi2023safeis': dict(tags=['safety', 'cbf'], tldr='SC-MPPI: embeds a barrier-state safety controller in forward sampling so rollouts stay safe, increasing sample efficiency.', method='Barrier states inside rollouts; information-theoretic derivation.', evidence='Simulated navigation.', relevance='Safety inside sampling rather than after.', concepts=['concepts/constraints-and-safety']),
'rabiee2025gsmppi': dict(tags=['safety', 'cbf'], tldr='GS-MPPI: composite CBF builds a single safe closed-form controller integrated into dynamics so all sampled trajectories are provably safe.', method='Composite CBF, safe control law inside rollouts.', evidence='Nonholonomic ground robot simulation.', relevance='Provable safety for AMRs under multiple constraints.', concepts=['concepts/constraints-and-safety', 'applications/mobile-robots-amr']),
'parwana2025brmppi': dict(tags=['safety', 'cbf'], tldr='BR-MPPI: CBF condition as equality with learnable class-K parameter treated as extra input; samples projected onto constraint manifold.', method='Barrier-rate augmentation, projection of sampled controls.', evidence='Simulations with learned SDFs, hardware.', relevance='Multiple constraints with learned distance fields.', concepts=['concepts/constraints-and-safety']),
'yin2024ccmppi': dict(tags=['safety', 'chance-constraints'], tldr='BSS-MPPI: belief-space stochastic MPPI enforcing chance constraints with a CBF-inspired heuristic, no linearisation.', method='Monte-Carlo belief propagation, chance constraints.', evidence='Race-car simulation.', relevance='Probabilistic safety, relevant for uncertain human predictions.', concepts=['concepts/constraints-and-safety', 'concepts/robustness-uncertainty']),
'kim2022smppi': dict(tags=['smoothness'], tldr='Smooth-MPPI: samples in the derivative-action space (input lifting) to obtain smooth commands without post-hoc smoothing.', method='Action-derivative sampling with smoothness cost.', evidence='Pendulum, autonomous driving with NN dynamics.', relevance='Smooth references are mandatory for industrial axes.', concepts=['concepts/smoothness-action-parametrization']),
'mohamed2022logmppi': dict(tags=['sampling', 'mobile'], tldr='log-MPPI: normal-log-normal mixture noise for better exploration; navigation of AGVs in unknown cluttered environments with local costmaps.', method='NLN sampling distribution.', evidence='2D navigation sims, real AGV.', relevance='Directly targets AGVs with costmaps.', concepts=['concepts/sampling-distributions', 'applications/mobile-robots-amr']),
'mohamed2023gpmppi': dict(tags=['mobile', 'guidance'], tldr='GP-MPPI: sparse Gaussian process perception model proposes subgoals to MPPI beyond its horizon.', method='SGP variance surface, subgoal selection.', evidence='Simulated and real navigation.', relevance='Local-global coupling for AMRs without a global map.', concepts=['applications/mobile-robots-amr', 'concepts/sampling-distributions']),
'trevisan2024biasedmppi': dict(tags=['sampling', 'mobile', 'guidance'], tldr='Biased-MPPI: derivation of MPPI for arbitrary sampling distributions; mixes samples from ancillary controllers (classical, learned) for informative sampling.', method='Importance sampling with arbitrary proposals, control fusion.', evidence='Simulated and real (mobile robots, driving).', relevance='Mechanism to inject Open-IPC global paths as proposals.', concepts=['concepts/sampling-distributions', 'concepts/hybrid-gradient-sampling', 'comparisons/plan4ari-gap-analysis']),
'asmar2023mpopi': dict(tags=['sampling'], tldr='MPOPI: adaptive importance sampling iterations within MPPI for better proposal.', method='Adaptive importance sampling / PMC iterations.', evidence='Simulated tasks.', relevance='Sample efficiency.', concepts=['concepts/sampling-distributions']),
'honda2024svgmppi': dict(tags=['multimodal', 'mobile'], tldr='SVG-MPPI: SVGD identifies a target mode, MPPI then converges on that mode only (mode-seeking).', method='SVGD-guided proposal + MPPI.', evidence='Fast vehicle sim and real.', relevance='Avoids mode averaging while keeping MPPI speed.', concepts=['concepts/multimodality']),
'liu2026clusteringmppi': dict(tags=['multimodal', 'manipulators'], tldr='CE-MPPI: DBSCAN clustering of rollouts with a geometric direction feature isolates feasible modes and avoids averaging-induced failure.', method='Prune and cluster rollouts, choose mode by cost/obstacle flux.', evidence='2D JAX sims; real UR5e with Isaac Gym rollouts (-48% time-to-goal, -12% path).', relevance='Fixes the main weakness of M3P2I blending.', concepts=['concepts/multimodality', 'applications/industrial-manipulators']),
'sacks2023learningsampling': dict(tags=['learning', 'sampling'], tldr='Learns sampling distributions for MPC (normalising flows) from data to improve sample efficiency.', method='Learned proposal distributions.', evidence='Simulated tasks.', relevance='Learned proposals for repetitive industrial cells.', concepts=['concepts/learning-augmented-mppi', 'concepts/sampling-distributions']),
'aoyama2026hybrid': dict(tags=['hybrid', 'ddp'], tldr='ME-DDP: alternates DDP gradient steps with sampling from inverse-Hessian policies (unimodal, multimodal, Stein) to escape local minima; benchmarked against MPPI.', method='Maximum-entropy DDP variants.', evidence='Navigation of four robotic systems in clutter.', relevance='Evidence for gradient+sampling hybrids.', concepts=['concepts/hybrid-gradient-sampling', 'concepts/mppi-vs-mpc']),
'xue2025dialmpc': dict(tags=['diffusion', 'locomotion'], tldr='DIAL-MPC: diffusion-style annealing of MPPI noise for full-order torque-level sampling MPC.', method='Annealed multi-iteration MPPI.', evidence='Quadruped hardware.', relevance='Annealing for high-dimensional systems (whole-body).', concepts=['concepts/sampling-distributions', 'concepts/hybrid-gradient-sampling']),
'pan2024mbd': dict(tags=['diffusion'], tldr='Model-based diffusion: trajectory optimisation as score-based denoising using the model, no data needed.', method='Monte-Carlo score estimation.', evidence='Simulated tasks.', relevance='Theoretical link MPPI <-> diffusion.', concepts=['concepts/sampling-distributions']),
'lowrey2019polo': dict(tags=['learning'], tldr='POLO: MPPI planning with learned value function as terminal cost and optimistic exploration.', method='MPPI + value ensemble.', evidence='Humanoid, hand manipulation sims.', relevance='Terminal value extends short horizons.', concepts=['concepts/learning-augmented-mppi']),
'bhardwaj2020mpq': dict(tags=['learning'], tldr='MPQ: information-theoretic MPC combined with soft Q-learning; MPPI with learned terminal Q.', method='Soft Q terminal cost.', evidence='Simulated manipulation and control.', relevance='Theory of MPC + RL combination.', concepts=['concepts/learning-augmented-mppi']),
'hansen2022tdmpc': dict(tags=['learning'], tldr='TD-MPC: latent world model + TD-learned value; plans with MPPI in latent space.', method='Latent MPPI with learned terminal value.', evidence='DMControl, Meta-World.', relevance='Learning-based MPPI for long-horizon tasks.', concepts=['concepts/learning-augmented-mppi']),
# ------------------------------------------------------------------ manipulators
'bhardwaj2021storm': dict(tags=['manipulators', 'gpu', 'software'], tldr='STORM: GPU joint-space MPPI for 7-DoF arms with learned self-collision and SDF costs, Halton-spline sampling; 125 Hz with task and joint constraints.', method='Batched kinematics on GPU, MPPI with Halton splines, cost terms for limits/collisions.', evidence='Franka real-world reactive reaching, pose tracking, obstacle avoidance.', relevance='Reference architecture for MPPI on industrial arms.', concepts=['applications/industrial-manipulators', 'tools/software-ecosystem', 'concepts/smoothness-action-parametrization']),
'sundaralingam2023curobo': dict(tags=['manipulators', 'gpu', 'software', 'hybrid'], tldr='cuRobo: GPU-parallel collision-free motion generation: parallel IK, geometric planner, particle-based (MPPI-like) seeding + L-BFGS; ~30-50 ms per plan.', method='Batched particle optimisation + L-BFGS with parallel line search.', evidence='Benchmarks vs SOTA planners; real robots.', relevance='Industrial-grade GPU motion generation; hybrid sampling+gradient.', concepts=['applications/industrial-manipulators', 'concepts/hybrid-gradient-sampling', 'tools/software-ecosystem']),
'jankowski2023vpsto': dict(tags=['manipulators', 'trajopt'], tldr='VP-STO: stochastic (CMA-ES) optimisation over via-points with time-optimal smooth trajectories, used in MPC for reactive behaviour.', method='Via-point parametrisation, CMA-ES.', evidence='Franka reactive tasks.', relevance='Industrial-friendly trajectory representation for sampling MPC.', concepts=['concepts/smoothness-action-parametrization', 'applications/industrial-manipulators']),
'pezzato2025isaacmppi': dict(tags=['manipulators', 'mobile-manipulation', 'simulator'], tldr='MPPI with IsaacGym as dynamics model: no explicit dynamics/contact modelling; navigation, pushing and whole-body control at 25 Hz with 750 parallel envs.', method='GPU physics simulator rollouts, Halton splines, open-source m3p2i-aip code base.', evidence='Sim and real: omnidirectional and differential-drive bases, fixed and mobile manipulators (Panda).', relevance='Basis of M3P2I; simulator-in-the-loop for contact tasks.', concepts=['concepts/physics-simulator-rollouts', 'applications/mobile-manipulation-tamp', 'applications/industrial-manipulators']),
'dierking2026parallelsbmpc': dict(tags=['manipulators', 'contact', 'simulator'], tldr='Real-world JAX + MuJoCo-MJX sampling MPC on Franka FR3 for Push-T; structured multimodal sampling (MTP) beats CEM/MPPI/PS; online domain randomisation analysed.', method='Massively parallel MJX rollouts, real-to-sim-to-real pipeline, MoveIt Servo at 1 kHz.', evidence='Sim and hardware; planning at 8-10 Hz on RTX 5090.', relevance='Honest assessment of compute and contact-model limits.', concepts=['concepts/physics-simulator-rollouts', 'concepts/multimodality', 'applications/industrial-manipulators']),
'im2026torquemppi': dict(tags=['manipulators', 'torque', 'hri'], tldr='Torque-sampling MPPI task-space control with full rigid-body dynamics and safety constraints; compliant, force-aware behaviour at >166 Hz, 0.18 s horizon.', method='Torque sampling on GPU, task-space costs, safety constraints.', evidence='Real 7-DoF manipulator.', relevance='MPPI at torque level for physical HRI.', concepts=['applications/industrial-manipulators', 'applications/human-robot-shared-spaces']),
'lee2026prmppi': dict(tags=['manipulators', 'constraints'], tldr='PR-MPPI: projects sampled velocities onto equality (closed chain) and inequality (limits, clearance) constraints, then retracts onto the manifold: exact constraint satisfaction.', method='Projection-retraction inside rollouts.', evidence='14-DoF dual-arm sims; Unitree H1-2 arms real.', relevance='Hard joint/workspace constraints in MPPI without penalties.', concepts=['concepts/constraints-and-safety', 'applications/industrial-manipulators']),
'gursoy2026cosmik': dict(tags=['manipulators', 'hri', 'safety'], tldr='COSMIK-MPPI: MPPI + RT-COSMIK markerless human pose + constraints-as-terminations; 100% success at constant 22 ms, outperforming gradient-based MPC.', method='Constraint violation terminates rollout; no human motion prediction needed.', evidence='Sim (incl. infeasible scenarios) and real HRI on torque-controlled arm.', relevance='Most direct precedent for ISO/TS 15066-aware MPPI.', concepts=['concepts/constraints-and-safety', 'applications/human-robot-shared-spaces', 'applications/industrial-manipulators']),
# ------------------------------------------------------------------ mobile
'macenski2023nav2survey': dict(tags=['mobile', 'software', 'industrial'], tldr='Survey of modern ROS 2 mobile-robotics algorithms by Nav2 maintainers; MPPI controller described as major improvement over reactive methods, rarely needs recovery, planned as default.', method='Survey / software description.', evidence='Field experience of Nav2 deployments.', relevance='Industrial adoption evidence for AMRs.', concepts=['applications/mobile-robots-amr', 'tools/software-ecosystem']),
'testouri2023mppiad': dict(tags=['mobile', 'driving'], tldr='MPPI-based real-time safe motion planning framework for autonomous driving (Frenet/road constraints).', method='MPPI with driving-specific costs and safety layer.', evidence='Simulation.', relevance='Structured-environment MPPI design patterns.', concepts=['applications/mobile-robots-amr']),
'trevisan2025drampi': dict(tags=['mobile', 'hri', 'safety'], tldr='DRA-MPPI: Monte-Carlo joint collision probability against non-Gaussian human predictions for hundreds of rollouts in real time; sample rejection or CP cost.', method='MC collision probability per rollout.', evidence='Real and simulated crowds.', relevance='Human-aware AMR navigation, mitigates freezing robot.', concepts=['applications/human-robot-shared-spaces', 'applications/mobile-robots-amr', 'concepts/constraints-and-safety']),
'jansma2023interaction': dict(tags=['mobile', 'multi-agent'], tldr='Interaction-aware sampling-based MPC with learned local-goal predictions of other agents.', method='MPPI + learned goal prediction.', evidence='Simulated multi-agent navigation scenarios.', relevance='Fleet / human interaction for AMRs.', concepts=['applications/mobile-robots-amr', 'applications/human-robot-shared-spaces']),
'streichenberg2023mapi': dict(tags=['mobile', 'multi-agent'], tldr='Multi-agent path-integral control for interaction-aware planning of autonomous vessels in urban canals.', method='Joint sampling over agents, cooperative cost.', evidence='Simulation.', relevance='Multi-agent MPPI template for AMR fleets.', concepts=['applications/mobile-robots-amr']),
'jung2024contingency': dict(tags=['mobile', 'safety'], tldr='Contingency-MPPI: nested MPPI ensures a contingency (fallback) plan always exists; adaptive importance sampling and warm-start from a light planner.', method='MPPI within MPPI.', evidence='Sim and hardware mobile robot.', relevance='Fallback strategies required by D4.1 Sect. 5.', concepts=['concepts/constraints-and-safety', 'applications/mobile-robots-amr']),
'desai2026fpgampi': dict(tags=['mobile', 'hardware'], tldr='FPGA-optimised MPPI: deep pipelining; 3.1-7.5x faster and 2.5-5.4x less energy than embedded GPU/CPU.', method='FPGA architecture.', evidence='AMR benchmarks.', relevance='Deterministic, low-power MPPI for embedded industrial controllers.', concepts=['tools/software-ecosystem', 'applications/mobile-robots-amr']),
# ------------------------------------------------------------------ TAMP / mobile manipulation
'zhang2024m3p2i': dict(tags=['tamp', 'multimodal', 'mobile-manipulation', 'key-paper'], tldr='M3P2I: Active Inference planner returns N alternative symbolic plans -> N cost functions; multi-modal MPPI samples N*K rollouts in IsaacGym, per-mode weights with auto-tuned temperature, blended into one command. Reactive push/pull and pick-place.', method='AIP + BT (1 Hz), plan interface (action->cost), M3P2I (25 Hz) with Halton splines, per-mode beta_i so eta_i in 5-10% of K, joint re-weighting.', evidence='Push-pull omni base: multimodal 0.1052 pos err, 0.0041 ori err, 3.8 s vs push 6.2 s / pull 25.1 s; corner case push times out. Pick-place reactive: 0.0117 vs RL 0.0246. Real Franka experiments with disturbances.', relevance='Key paper for Plan4ARI: alternative strategies sampled at motion level. Limits: blending may average modes, soft constraints, N*K physics cost, no human safety.', concepts=['concepts/multimodality', 'applications/mobile-manipulation-tamp', 'concepts/physics-simulator-rollouts']),
'pezzato2023aip': dict(tags=['tamp', 'task-planning'], tldr='Active inference + behaviour trees for reactive action planning and execution in robotics.', method='Free-energy minimisation over symbolic beliefs; BT encodes desired states.', evidence='Simulated and real mobile-manipulation tasks.', relevance='High-level planner in M3P2I; candidate interface to Activity 2.', concepts=['applications/mobile-manipulation-tamp']),
'makoviychuk2021isaacgym': dict(tags=['simulator', 'software'], tldr='Isaac Gym: GPU physics simulation with tensor API for thousands of parallel environments.', method='Software.', evidence='RL benchmarks.', relevance='Rollout engine for Pezzato et al. / M3P2I.', concepts=['concepts/physics-simulator-rollouts', 'tools/software-ecosystem']),
'vlahov2024mppigeneric': dict(tags=['software', 'gpu'], tldr='MPPI-Generic: header-only CUDA C++ library for MPPI, Tube-MPPI, RMPPI with plug-in dynamics and costs.', method='Software library.', evidence='Timing benchmarks vs other implementations.', relevance='Candidate production-grade backend.', concepts=['tools/software-ecosystem']),
}
