# D4.1: XeLaTeX (Cambria/Calibri system fonts), shared Project Reporting config
$root   = '../../..';
$engine = 'xelatex';
do "$root/latexmkrc";

# SOTA macros and bibliography
ensure_path('TEXINPUTS', '../SOTA/latex//');
bib_dirs('../SOTA/latex');
